version: "3"

services:
  optiiscan:
    container_name: optiiscan
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./tailwind.config.js:/app/tailwind.config.js
    ports:
      - 3000:3000

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017  # Maps host port 27018 to container port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: optiiscan
    command: --quiet
    volumes:
      - ./src/lib/server/db/init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongo:27017/
